### ISSUE TITLE
what's the meaning about these numbers?

### ISSUE THREAD

**Issue by chaihongjun** [ullmark/grunt-ucss#8]
who can tell me  what is these numbers?
![qq 20160930100226](https://cloud.githubusercontent.com/assets/12774598/18978406/801b73e6-86f5-11e6-89d7-f100a5754b83.png)

**Comment by ullmark** [comment]
Hi there, 
It is the line numbers (position) returned from ucss of where the selector was found. 
https://github.com/ullmark/grunt-ucss/blob/master/tasks/ucss.js#L46

**Comment by chaihongjun** [comment]
@ullmark  thank u.Oh, I see. That's why.
And I have another question .Can I export the results  to the document?

**Comment by ullmark** [comment]
@chaihongjun seems a bit strange that you get "html" in the list of unused selectors...  Are you testing it against a document not containing a `<html>`-tag? 

> Can I export the results to the document?

not sure what you mean, export results how and why?

**Comment by ullmark** [comment]
@chaihongjun I will also have to warn you, I am not actively supporting/working on this plugin. However, the plugin doesn't contain much code so it should be easy to move this out to a custom task (or whatever it was called in Grunt) if you want to make changes to it...

Or send a pull request to this repo..

**Comment by chaihongjun** [comment]
@ullmark  yeah,I mean  I want to export the  task resutls from the console to a file,like export.txt  etc....
then I can check errors or warnings  easily.

**Comment by ullmark** [comment]
I see... No, there is nothing built into this grunt plugin that allows exporting to a file.

**Comment by chaihongjun** [comment]
@ullmark  Thank u very much!!!
